package com.jshop.entity;

// Generated 2013-3-22 15:24:47 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoodsTypeT generated by hbm2java
 */
@Entity
@Table(name = "goods_type_t", catalog = "jshoper3")
public class GoodsTypeT implements java.io.Serializable {

	private String id;
	private String navid;
	private String nname;
	private String ltypeid;
	private String lname;
	private String stypeid;
	private String sname;
	private String fname;
	private String navigation;
	private Date createtime;
	private String creatorid;
	private String state;

	public GoodsTypeT() {
	}

	public GoodsTypeT(String id, Date createtime, String creatorid, String state) {
		this.id = id;
		this.createtime = createtime;
		this.creatorid = creatorid;
		this.state = state;
	}

	public GoodsTypeT(String id, String navid, String nname, String ltypeid, String lname, String stypeid, String sname, String fname, String navigation, Date createtime, String creatorid, String state) {
		this.id = id;
		this.navid = navid;
		this.nname = nname;
		this.ltypeid = ltypeid;
		this.lname = lname;
		this.stypeid = stypeid;
		this.sname = sname;
		this.fname = fname;
		this.navigation = navigation;
		this.createtime = createtime;
		this.creatorid = creatorid;
		this.state = state;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAVID", length = 20)
	public String getNavid() {
		return this.navid;
	}

	public void setNavid(String navid) {
		this.navid = navid;
	}

	@Column(name = "NNAME", length = 50)
	public String getNname() {
		return this.nname;
	}

	public void setNname(String nname) {
		this.nname = nname;
	}

	@Column(name = "LTYPEID", length = 20)
	public String getLtypeid() {
		return this.ltypeid;
	}

	public void setLtypeid(String ltypeid) {
		this.ltypeid = ltypeid;
	}

	@Column(name = "LNAME", length = 50)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "STYPEID", length = 20)
	public String getStypeid() {
		return this.stypeid;
	}

	public void setStypeid(String stypeid) {
		this.stypeid = stypeid;
	}

	@Column(name = "SNAME", length = 50)
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	@Column(name = "FNAME", length = 50)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "NAVIGATION", length = 20)
	public String getNavigation() {
		return this.navigation;
	}

	public void setNavigation(String navigation) {
		this.navigation = navigation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", nullable = false, length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATORID", nullable = false, length = 20)
	public String getCreatorid() {
		return this.creatorid;
	}

	public void setCreatorid(String creatorid) {
		this.creatorid = creatorid;
	}

	@Column(name = "STATE", nullable = false, length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
