package com.jshop.entity;

// Generated 2013-5-19 18:50:11 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PageEditareaT generated by hbm2java
 */
@Entity
@Table(name = "page_editarea_t", catalog = "jshoper3")
public class PageEditareaT implements java.io.Serializable {

	private String pageeditareaid;
	private String goodscategoryid;
	private String name;
	private String sign;
	private String htmlpath;
	private String editareatitle;
	private String editareavalue;
	private Integer editflag;
	private String state;
	private String snid;
	private String creatorid;
	private Date createtime;

	public PageEditareaT() {
	}

	public PageEditareaT(String pageeditareaid, String name, String sign,
			String editareatitle) {
		this.pageeditareaid = pageeditareaid;
		this.name = name;
		this.sign = sign;
		this.editareatitle = editareatitle;
	}

	public PageEditareaT(String pageeditareaid, String goodscategoryid,
			String name, String sign, String htmlpath, String editareatitle,
			String editareavalue, Integer editflag, String state, String snid,
			String creatorid, Date createtime) {
		this.pageeditareaid = pageeditareaid;
		this.goodscategoryid = goodscategoryid;
		this.name = name;
		this.sign = sign;
		this.htmlpath = htmlpath;
		this.editareatitle = editareatitle;
		this.editareavalue = editareavalue;
		this.editflag = editflag;
		this.state = state;
		this.snid = snid;
		this.creatorid = creatorid;
		this.createtime = createtime;
	}

	@Id
	@Column(name = "PAGEEDITAREAID", unique = true, nullable = false, length = 20)
	public String getPageeditareaid() {
		return this.pageeditareaid;
	}

	public void setPageeditareaid(String pageeditareaid) {
		this.pageeditareaid = pageeditareaid;
	}

	@Column(name = "GOODSCATEGORYID", length = 20)
	public String getGoodscategoryid() {
		return this.goodscategoryid;
	}

	public void setGoodscategoryid(String goodscategoryid) {
		this.goodscategoryid = goodscategoryid;
	}

	@Column(name = "NAME", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SIGN", nullable = false, length = 45)
	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	@Column(name = "HTMLPATH")
	public String getHtmlpath() {
		return this.htmlpath;
	}

	public void setHtmlpath(String htmlpath) {
		this.htmlpath = htmlpath;
	}

	@Column(name = "EDITAREATITLE", nullable = false, length = 45)
	public String getEditareatitle() {
		return this.editareatitle;
	}

	public void setEditareatitle(String editareatitle) {
		this.editareatitle = editareatitle;
	}

	@Column(name = "EDITAREAVALUE", length = 65535)
	public String getEditareavalue() {
		return this.editareavalue;
	}

	public void setEditareavalue(String editareavalue) {
		this.editareavalue = editareavalue;
	}

	@Column(name = "EDITFLAG")
	public Integer getEditflag() {
		return this.editflag;
	}

	public void setEditflag(Integer editflag) {
		this.editflag = editflag;
	}

	@Column(name = "STATE", length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "SNID", length = 20)
	public String getSnid() {
		return this.snid;
	}

	public void setSnid(String snid) {
		this.snid = snid;
	}

	@Column(name = "CREATORID", length = 20)
	public String getCreatorid() {
		return this.creatorid;
	}

	public void setCreatorid(String creatorid) {
		this.creatorid = creatorid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
