package com.jshop.entity;

// Generated 2013-3-22 15:24:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaobaoUserT generated by hbm2java
 */
@Entity
@Table(name = "taobao_user_t", catalog = "jshoper3")
public class TaobaoUserT implements java.io.Serializable {

	private String taobaoUserid;
	private String taobaoNick;

	public TaobaoUserT() {
	}

	public TaobaoUserT(String taobaoUserid, String taobaoNick) {
		this.taobaoUserid = taobaoUserid;
		this.taobaoNick = taobaoNick;
	}

	@Id
	@Column(name = "taobao_userid", unique = true, nullable = false, length = 100)
	public String getTaobaoUserid() {
		return this.taobaoUserid;
	}

	public void setTaobaoUserid(String taobaoUserid) {
		this.taobaoUserid = taobaoUserid;
	}

	@Column(name = "taobao_nick", nullable = false, length = 100)
	public String getTaobaoNick() {
		return this.taobaoNick;
	}

	public void setTaobaoNick(String taobaoNick) {
		this.taobaoNick = taobaoNick;
	}

}
