package com.jshop.entity;

// Generated 2014-10-9 18:51:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoodsCardsPasswordT generated by hbm2java
 */
@Entity
@Table(name = "goods_cards_password_t", catalog = "jshoper3")
public class GoodsCardsPasswordT implements java.io.Serializable {

	private String id;
	private String goodsCardsId;
	private String password;
	private String status;
	private Date createtime;
	private Date updatetime;
	private String memberid;

	public GoodsCardsPasswordT() {
	}

	public GoodsCardsPasswordT(String id, String goodsCardsId, String password,
			String status) {
		this.id = id;
		this.goodsCardsId = goodsCardsId;
		this.password = password;
		this.status = status;
	}

	public GoodsCardsPasswordT(String id, String goodsCardsId, String password,
			String status, Date createtime, Date updatetime, String memberid) {
		this.id = id;
		this.goodsCardsId = goodsCardsId;
		this.password = password;
		this.status = status;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.memberid = memberid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "GOODS_CARDS_ID", nullable = false, length = 20)
	public String getGoodsCardsId() {
		return this.goodsCardsId;
	}

	public void setGoodsCardsId(String goodsCardsId) {
		this.goodsCardsId = goodsCardsId;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", length = 0)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "MEMBERID", length = 20)
	public String getMemberid() {
		return this.memberid;
	}

	public void setMemberid(String memberid) {
		this.memberid = memberid;
	}

}
