package com.jshop.entity;

// Generated 2013-8-11 9:45:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InvoicetempleteT generated by hbm2java
 */
@Entity
@Table(name = "invoicetemplete_t", catalog = "jshoper3")
public class InvoicetempleteT implements java.io.Serializable {

	private String invoicetempleteid;
	private String logisticsid;
	private String state;
	private String kindeditorCode;

	public InvoicetempleteT() {
	}

	public InvoicetempleteT(String invoicetempleteid, String state,
			String kindeditorCode) {
		this.invoicetempleteid = invoicetempleteid;
		this.state = state;
		this.kindeditorCode = kindeditorCode;
	}

	public InvoicetempleteT(String invoicetempleteid, String logisticsid,
			String state, String kindeditorCode) {
		this.invoicetempleteid = invoicetempleteid;
		this.logisticsid = logisticsid;
		this.state = state;
		this.kindeditorCode = kindeditorCode;
	}

	@Id
	@Column(name = "INVOICETEMPLETEID", unique = true, nullable = false, length = 20)
	public String getInvoicetempleteid() {
		return this.invoicetempleteid;
	}

	public void setInvoicetempleteid(String invoicetempleteid) {
		this.invoicetempleteid = invoicetempleteid;
	}

	@Column(name = "LOGISTICSID", length = 20)
	public String getLogisticsid() {
		return this.logisticsid;
	}

	public void setLogisticsid(String logisticsid) {
		this.logisticsid = logisticsid;
	}

	@Column(name = "STATE", nullable = false, length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "KINDEDITOR_CODE", nullable = false, length = 65535)
	public String getKindeditorCode() {
		return this.kindeditorCode;
	}

	public void setKindeditorCode(String kindeditorCode) {
		this.kindeditorCode = kindeditorCode;
	}

}
