package com.jshop.entity;

// Generated 2014-10-9 18:51:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WeixinMemberTagT generated by hbm2java
 */
@Entity
@Table(name = "weixin_member_tag_t", catalog = "jshoper3")
public class WeixinMemberTagT implements java.io.Serializable {

	private String id;
	private String tagname;
	private Date createtime;
	private Date updatetime;
	private String statue;

	public WeixinMemberTagT() {
	}

	public WeixinMemberTagT(String id, String tagname, Date createtime,
			Date updatetime, String statue) {
		this.id = id;
		this.tagname = tagname;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.statue = statue;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "TAGNAME", nullable = false, length = 64)
	public String getTagname() {
		return this.tagname;
	}

	public void setTagname(String tagname) {
		this.tagname = tagname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", nullable = false, length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", nullable = false, length = 0)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "STATUE", nullable = false, length = 1)
	public String getStatue() {
		return this.statue;
	}

	public void setStatue(String statue) {
		this.statue = statue;
	}

}
