package com.jshop.entity;

// Generated 2014-9-29 15:34:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WexinCompanyBaseCpT generated by hbm2java
 */
@Entity
@Table(name = "wexin_company_base_cp_t", catalog = "jshoper3")
public class WexinCompanyBaseCpT implements java.io.Serializable {

	private String id;
	private String corpid;
	private String corpsecret;
	private String companyname;
	private Date createtime;
	private Date updatetime;
	private String creatorid;
	private String statue;
	private String mode;
	private String url;
	private String token;
	private String encodingaeskey;

	public WexinCompanyBaseCpT() {
	}

	public WexinCompanyBaseCpT(String id, String corpid, String corpsecret,
			String companyname, Date createtime, Date updatetime,
			String creatorid, String statue, String mode, String url,
			String token, String encodingaeskey) {
		this.id = id;
		this.corpid = corpid;
		this.corpsecret = corpsecret;
		this.companyname = companyname;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.creatorid = creatorid;
		this.statue = statue;
		this.mode = mode;
		this.url = url;
		this.token = token;
		this.encodingaeskey = encodingaeskey;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CORPID", nullable = false, length = 45)
	public String getCorpid() {
		return this.corpid;
	}

	public void setCorpid(String corpid) {
		this.corpid = corpid;
	}

	@Column(name = "CORPSECRET", nullable = false, length = 512)
	public String getCorpsecret() {
		return this.corpsecret;
	}

	public void setCorpsecret(String corpsecret) {
		this.corpsecret = corpsecret;
	}

	@Column(name = "COMPANYNAME", nullable = false, length = 100)
	public String getCompanyname() {
		return this.companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", nullable = false, length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", nullable = false, length = 0)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "CREATORID", nullable = false, length = 20)
	public String getCreatorid() {
		return this.creatorid;
	}

	public void setCreatorid(String creatorid) {
		this.creatorid = creatorid;
	}

	@Column(name = "STATUE", nullable = false, length = 1)
	public String getStatue() {
		return this.statue;
	}

	public void setStatue(String statue) {
		this.statue = statue;
	}

	@Column(name = "MODE", nullable = false, length = 45)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "URL", nullable = false, length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "TOKEN", nullable = false, length = 32)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "ENCODINGAESKEY", nullable = false, length = 45)
	public String getEncodingaeskey() {
		return this.encodingaeskey;
	}

	public void setEncodingaeskey(String encodingaeskey) {
		this.encodingaeskey = encodingaeskey;
	}

}
